site_name: K20s Documentation
repo_url: https://github.com/OpScaleHub/K20s
repo_name: OpScaleHub/K20s

theme:
  name: material
  palette:
    - scheme: slate
      primary: 'indigo'
      accent: 'light-blue'
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      primary: 'indigo'
      accent: 'light-blue'
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  font:
    text: 'Inter'
    code: 'SFMono-Regular'
  logo: 'assets/logo.svg'
  favicon: 'assets/logo.svg'

nav:
  - 'Home': 'index.md'
  - 'Makefile Commands': 'make-help.md'
  - 'API Reference': 'api-reference.md'

docs_dir: docs-src
site_dir: docs/generated

extra_css:
  - stylesheets/extra.css