# This rule is not used by the project k20s itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over optimizer.example.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k20s
    app.kubernetes.io/managed-by: kustomize
  name: resourceoptimizerprofile-admin-role
rules:
- apiGroups:
  - optimizer.example.com
  resources:
  - resourceoptimizerprofiles
  verbs:
  - '*'
- apiGroups:
  - optimizer.example.com
  resources:
  - resourceoptimizerprofiles/status
  verbs:
  - get
