# This rule is not used by the project k20s itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the optimizer.example.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k20s
    app.kubernetes.io/managed-by: kustomize
  name: resourceoptimizerprofile-editor-role
rules:
- apiGroups:
  - optimizer.example.com
  resources:
  - resourceoptimizerprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - optimizer.example.com
  resources:
  - resourceoptimizerprofiles/status
  verbs:
  - get
