apiVersion: optimizer.k20s.opscale.ir/v1
kind: ResourceOptimizerProfile
metadata:
  name: resourceoptimizerprofile-sample
  namespace: default
spec:
  selector:
    matchLabels:
      app: test-app
  cpuThresholds:
    min: 10
    max: 75
  optimizationPolicy: Scale
  cooldownPeriod: 1m
