apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k20s.fullname" . }}-metrics-auth
  labels:
    {{- include "k20s.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k20s.fullname" . }}-metrics-auth-role
subjects:
- kind: ServiceAccount
  name: {{ include "k20s.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
