apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k20s.serviceAccountName" . }}
  labels:
    {{- include "k20s.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
